### ISSUE TITLE
PR: Add execPath option to set path to docker-compose executable

### ISSUE THREAD

**Issue by Mrono** [PDMLab/docker-compose#149]
I've ran into an issue that caused a need for this feature.  I have the commits made on my fork, what is the next steps for a PR?

You can see my changes here https://github.com/PDMLab/docker-compose/compare/master...Mrono:execPath-option?expand=1

**Comment by Steveb-p** [comment]
@Mrono you can use the link you've provided to open a PR to this repository :smile: 

It's literally right there :smile: 

![image](https://user-images.githubusercontent.com/3183926/117421881-4320c480-af1f-11eb-92ac-9eae7e920d61.png)

Just put a sensible title/description and you're good to go, there are no guidelines how those should be structured at the moment.

**Comment by Mrono** [comment]
I've created the PR now https://github.com/PDMLab/docker-compose/pull/152

I was waiting to create the PR for feedback as per the readme

**Comment by Steveb-p** [comment]
Oh, I've never noticed that note :smile: 

In this particular case I'd say it's ok to open a PR immediately: after all, it's a specific functionality you're asking for that can have code provided instantly (as you were using a patched version anyway). It's more for feature requests I guess that may or may not be accepted, since sometimes open source software can get weird requests that go way beyond the scope of the project :smile:

**Comment by Mrono** [comment]
Merged into version 0.23.9. Thanks for the help guys.
