### ISSUE TITLE
doubt docker-compose

### ISSUE THREAD

**Issue by pedroricardo** [PDMLab/docker-compose#193]
Is there any possibility to use this lib together with dockerode?

to upload contatiners via docker-compose on remote hosts via a docker api with TLS authentication

**Comment by Steveb-p** [comment]
Dockerode uses Docker API directly. It communicates with Docker endpoint (socket or tcp).

This package uses `docker-compose` system binary, which in turn executes commands vs. Docker API. So they work on fundamentally different layers.

That being said, nothing stops you from using Dockerode inside the same code that uses this package.

If you simply want to communicate with a remote docker API, then what you want to do is provide an option (`--host`) when executing functions exposed here.

**Comment by pedroricardo** [comment]
thanks for the reply, leaving the dockerode aside and just using the docker-compose module. can I run the docker-compose module on a remote host?

Keeping in mind that my biggest problem is to copy the files to build the image and start the container on a remote host through a docker-compose.yml

Does your module accept options --host in compose.up() ?
is there any documentation on this somewhere on how i can make this work?

**Comment by AlexZeitler** [comment]
> Does your module accept options --host in compose.up() ?
> is there any documentation on this somewhere on how i can make this work?
> 

In general you can pass all `docker-compose` and all `docker-compose` command options to the lib.

`docker-compose` options like `--host` are called `composeOptions`: https://pdmlab.github.io/docker-compose/#options

You have to make sure you're using `composeOptions` because there are also `commandOptions` which vary by command.

**Comment by pedroricardo** [comment]
I understand, I managed to use --host in compose, now the problem is that I realized that the files that are in the COPY of the dockerfile are not copied to the remote host, so the container does not start (I need to send folders and some files.js) I don't know if there is any workaround to do this. I didn't want to have to use scp before docker-compose but if you don't have another way it will be the way.

**Comment by AlexZeitler** [comment]
A possible workaround: You could build the Image locally (using Dockerode) so that all required files are included. Then you push the images to a registry and after that you run `docker-compose` using the `--host` option and the host pulls the images from the registry now.

The other option would be using `scp` (either native or wrapped using Node `child_process`).

**Comment by pedroricardo** [comment]
docker-compose module supports --context argument

if so what is the correct way to pass it?
